### ISSUE TITLE
Voiceline works but Arms, Icons and names doesn't work

### ISSUE THREAD

**Issue by Edison1318** [justin-chellah/interactive-survivor-groups#1]
I got really excited to see someone made this plugin specifically turning the last four m_survivorCharacter enums into l4d2 survivors. Waited this for a very long time, but there's some downside too. For example one of the l4d2 survivor like Nick do recognize l4d2 survivor when you vocalize look on them but when they talk to the survivors it still recognize them as l4d1 survivors. Even mourning the l4d2 survivors as l4d1 instead.

Idk why the arms, icons and names doesn't work. Perhaps it could be client side issue and there's nothing else it could be fixed? It's still a good plugin btw.

**Comment by justin-chellah** [comment]
Could you make a video? I tested it earlier and I didn't see what's wrong with the mourning. Also not sure what you mean by survivors being recognized as L4D1 survivors.

Yeah, they're client-side and sadly there's nothing that can be done unless you hack the game. Names are changed though on the server side so you'll see it in the console for example, when they respawn as L4D2 survivors.

**Comment by Edison1318** [comment]
I realized the mourning is the caused of my plugin my apologies, the survivors can't mourn the dead survivors who are more than 3th enum of m_survivorCharacter.

Here's the video I recorded. 

https://github.com/justin-chellah/interactive-survivor-groups/assets/30228098/017cb5b2-d5d0-49f1-9dbe-a3c8700754cf

**Comment by justin-chellah** [comment]
Thanks for the report! I think I've fixed it. Can you test it and confirm?

[plugin.zip](https://github.com/justin-chellah/interactive-survivor-groups/files/12909743/plugin.zip)

**Comment by Edison1318** [comment]
Yup, I just tested it recently, they could respond to l4d2 survivors without an issue.

I do hope one day there's a chance to change survivor's names, icons and arms.
