### ISSUE TITLE
Issue still persist when the survivors tries to talk to l4d1 survivors. 

### ISSUE THREAD

**Issue by Edison1318** [justin-chellah/interactive-survivor-groups#2]
Yea, there's still bug going on and I'm sorry if I didn't fully debug completely. Here's the video I recorded to show how they respond.

https://github.com/justin-chellah/interactive-survivor-groups/assets/30228098/e7e8c2d7-696b-494c-a87d-eba3d0af47e4

**Comment by justin-chellah** [comment]
Hey, no problem. Thank you for the report! It's actually a mistake on my part, I completely forgot about the L4D1 survivors. It sometimes gets confusing when swapping numbers around. It should be fixed now; feel free to confirm!

[plugin-v2.zip](https://github.com/justin-chellah/interactive-survivor-groups/files/12915998/plugin-v2.zip)

**Comment by Edison1318** [comment]
It works like a charm, now the survivors should able to talk to l4d1 survivors. But there's the downside, not sure if it's me but I tried to call l4d1 survivor name by vocalizing "look" or smartlook on them but they kinda failed identifying as them. Sometimes they call them but its one of those lines they use to call when they are far away. The talker system is fine as it didn't show any issue when they're having conversations.

https://github.com/justin-chellah/interactive-survivor-groups/assets/30228098/ace87381-6958-4d41-9f15-e400dcc5fb9c

**Comment by justin-chellah** [comment]
Awesome. Yeah, I've noticed that too but wasn't sure if that was actually a vanilla bug but seems like that's not the case. It should be fixed as well now.

You'll need [SourceScramble](https://github.com/nosoop/SMExt-SourceScramble) for this version. Make sure to add these key/value pairs inside the "Patches" section to your `sourcescrambler_manager.cfg` file:
```
"interactive_survivor_groups" "Bill survivor character"
"interactive_survivor_groups" "Zoey survivor character"
"interactive_survivor_groups" "Francis survivor character"
"interactive_survivor_groups" "Louis survivor character"
```

Let me know if it's working for you!
[plugin-v3.zip](https://github.com/justin-chellah/interactive-survivor-groups/files/12926334/plugin-v3.zip)

**Comment by Edison1318** [comment]
Tested it, now that problem is fixed. I wouldn't want to bother you to fix one of the other criteria talkers, so this is already enough for the fix. 👍
